### ISSUE TITLE
Test is looking for a number to be 42. No other variables to set to 42.

### ISSUE THREAD

**Issue by ipbyrne** [learn-co-curriculum/dsc-1-01-07-working-with-lessons-on-learn-lab#1]
Test fails. Looking for a number to be 42. Only can set one number variable and it is asked to set to 27.

**Comment by ipbyrne** [comment]
Changing number to 42 still does not pass the test. Still logs 27 as the input.

**Comment by PeterBell** [comment]
Thanks so much for catching this @ipbyrne - fixed - I matched the copy to the number in the test. Thanks!
