### ISSUE TITLE
Pytest checks for number == 42, but notebook says to use 27

### ISSUE THREAD

**Issue by jirvingphd** [learn-co-curriculum/dsc-1-01-07-working-with-lessons-on-learn-lab#5]
Running pytest fails the user if they followed the notebook's instructions and set the variable number equal to 27. 

If I change my answer to 42, I pass the test, but this isn't what the instructions say to do. Please either change the notebook to instruct us to enter 42, or change the pytest to look for 27.

Thanks!

**Comment by mathymitchell** [comment]
Thanks for catching this typo; much appreciated!
